//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class AsuEq
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AsuEq()
        {
            this.Equipments = new HashSet<Equipments>();
            this.OpLogJournal = new HashSet<OpLogJournal>();
        }
    
        public int IdAsuEq { get; set; }
        public Nullable<int> IdAsuMainEq { get; set; }
        public string TagAsuEq { get; set; }
        public string NameAsuEq { get; set; }
        public string PlaceAsuEq { get; set; }
        public string PidAsuEq { get; set; }
        public string PlaceSchemeAsuEq { get; set; }
        public string Comments { get; set; }
        public Nullable<System.DateTime> MaintenancePeriod { get; set; }
        public Nullable<System.DateTime> NextMaintencePeriod { get; set; }
        public Nullable<System.DateTime> LastMaintencePeriod { get; set; }
        public string Sheme { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
        public Nullable<System.DateTime> UpdatedAt { get; set; }
    
        public virtual AsuMainEq AsuMainEq { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Equipments> Equipments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpLogJournal> OpLogJournal { get; set; }
    }
}
