//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpLogJournal
    {
        public int IdOpLogBook { get; set; }
        public Nullable<int> IdShift { get; set; }
        public string RecordingDate { get; set; }
        public string TimeOccurrence { get; set; }
        public string TimeSolution { get; set; }
        public Nullable<int> Emergency { get; set; }
        public Nullable<int> IdAsuEq { get; set; }
        public string Event { get; set; }
        public string WhatHappend { get; set; }
        public string WhatDoing { get; set; }
        public string Comments { get; set; }
        public string Writer { get; set; }
        public string Perfomers { get; set; }
    
        public virtual AsuEq AsuEq { get; set; }
        public virtual Shifts Shifts { get; set; }
    }
}
