
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------


namespace UpaProject.Models.DataFilesApp
{

using System;
    using System.Collections.Generic;
    
public partial class AsuMainEq
{

    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
    public AsuMainEq()
    {

        this.AsuEq = new HashSet<AsuEq>();

    }


    public int IdAsuMainEq { get; set; }

    public Nullable<int> IdItemsOfEq { get; set; }

    public string TagAsuMainEq { get; set; }

    public string NameAsuMainEq { get; set; }

    public string Comments { get; set; }

    public Nullable<System.DateTime> CreatedAt { get; set; }

    public Nullable<System.DateTime> UpdatedAt { get; set; }

    public string Writer { get; set; }



    [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]

    public virtual ICollection<AsuEq> AsuEq { get; set; }

    public virtual ItemsOfEq ItemsOfEq { get; set; }

}

}
