//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryStorages
    {
        public int ID { get; set; }
        public int IdUser { get; set; }
        public int IdStorage_MTR { get; set; }
        public Nullable<System.DateTime> DateEdit { get; set; }
        public string Activity { get; set; }
    
        public virtual Storage_MTR Storage_MTR { get; set; }
        public virtual Users Users { get; set; }
    }
}
