//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class HistoryLoginUsers
    {
        public int ID { get; set; }
        public int IdUser { get; set; }
        public System.DateTime DateLogin { get; set; }
    
        public virtual Users Users { get; set; }
    }
}
