//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class UpaDBEntities : DbContext
    {
        public UpaDBEntities()
            : base("name=UpaDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Departments> Departments { get; set; }
        public virtual DbSet<HistoryLoginUsers> HistoryLoginUsers { get; set; }
        public virtual DbSet<HistoryMTR> HistoryMTR { get; set; }
        public virtual DbSet<HistoryStorages> HistoryStorages { get; set; }
        public virtual DbSet<HistroyOpRecord> HistroyOpRecord { get; set; }
        public virtual DbSet<Images> Images { get; set; }
        public virtual DbSet<MTR> MTR { get; set; }
        public virtual DbSet<MTR_Images> MTR_Images { get; set; }
        public virtual DbSet<OpRececord> OpRececord { get; set; }
        public virtual DbSet<OpShifts> OpShifts { get; set; }
        public virtual DbSet<OpShifts_OpRecord> OpShifts_OpRecord { get; set; }
        public virtual DbSet<Persons> Persons { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Place_MTR> Place_MTR { get; set; }
        public virtual DbSet<PromActivites> PromActivites { get; set; }
        public virtual DbSet<Realizers> Realizers { get; set; }
        public virtual DbSet<RulesForRole> RulesForRole { get; set; }
        public virtual DbSet<Shifts_Persons> Shifts_Persons { get; set; }
        public virtual DbSet<StatusValues> StatusValues { get; set; }
        public virtual DbSet<Storage_MTR> Storage_MTR { get; set; }
        public virtual DbSet<Storages> Storages { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SystemsAsu> SystemsAsu { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WorkGroupValues> WorkGroupValues { get; set; }
    }
}
