//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTR
    {
        public int IdMTR { get; set; }
        public Nullable<int> IDSap { get; set; }
        public string Name { get; set; }
        public string Unit { get; set; }
    
        public virtual Storage_MTR Storage_MTR { get; set; }
    }
}
