//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTR_Images
    {
        public int ID { get; set; }
        public int IdMTR { get; set; }
        public int IdImage { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual MTR MTR { get; set; }
    }
}
