//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class MTR_Images
    {
        public int ID { get; set; }
        public int IdMTR { get; set; }
        public int IdImage { get; set; }
    
        public virtual Images Images { get; set; }
        public virtual MTR MTR { get; set; }
    }
}
