//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpShifts_OpRecord
    {
        public int ID { get; set; }
        public int IdShift { get; set; }
        public int IdOpRecord { get; set; }
    
        public virtual OpRececord OpRececord { get; set; }
        public virtual OpShifts OpShifts { get; set; }
    }
}
