//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Persons
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Persons()
        {
            this.Realizers = new HashSet<Realizers>();
            this.Shifts_Persons = new HashSet<Shifts_Persons>();
        }
    
        public int IDPerson { get; set; }
        public string Name { get; set; }
        public string Role { get; set; }
        public int IdStatus { get; set; }
        public int IdWorkGroup { get; set; }
    
        public virtual StatusValues StatusValues { get; set; }
        public virtual WorkGroupValues WorkGroupValues { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Realizers> Realizers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Shifts_Persons> Shifts_Persons { get; set; }
    }
}
