//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_MTR
    {
        public int ID { get; set; }
        public Nullable<int> IdPlace { get; set; }
        public Nullable<int> IdMTR { get; set; }
    
        public virtual MTR MTR { get; set; }
        public virtual Place Place { get; set; }
    }
}
