//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place_MTR
    {
        public int ID { get; set; }
        public Nullable<int> IdPlace { get; set; }
        public Nullable<int> IdMTR { get; set; }
    
        public virtual MTR MTR { get; set; }
        public virtual Place Place { get; set; }
    }
}
