//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Shifts_Persons
    {
        public int IDShifts_Persons { get; set; }
        public int IdShift { get; set; }
        public int IdPerson { get; set; }
    
        public virtual OpShifts OpShifts { get; set; }
        public virtual Persons Persons { get; set; }
    }
}
