//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_MTR
    {
        public int IdMTR { get; set; }
        public string Storage { get; set; }
        public Nullable<int> Quantity { get; set; }
    
        public virtual MTR MTR { get; set; }
        public virtual Storages Storages { get; set; }
    }
}
