//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpaProject.Models.DataFilesApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Storage_MTR
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Storage_MTR()
        {
            this.HistoryStorages = new HashSet<HistoryStorages>();
        }
    
        public int IDStorage_MTR { get; set; }
        public int IdMTR { get; set; }
        public int IdStorage { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Comment { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<HistoryStorages> HistoryStorages { get; set; }
        public virtual MTR MTR { get; set; }
        public virtual Storages Storages { get; set; }
    }
}
